# Generated by Django 5.1.6 on 2025-06-11 13:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0004_task_project_alter_task_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.JSONField(blank=True, default=list, verbose_name=models.CharField(choices=[('CR', 'Created'), ('UP', 'Updated'), ('SC', 'Status Changed'), ('DL', 'Deleted'), ('AC', 'Assignee Changed'), ('DC', 'Due Date Changed'), ('DE', 'Description Changed'), ('TC', 'Title Changed')], max_length=2))),
                ('field_changed', models.CharField(blank=True, max_length=50, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tasks.task')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Log',
                'verbose_name_plural': 'Task Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['task'], name='taskLogs_ta_task_id_2a84b9_idx'), models.Index(fields=['user'], name='taskLogs_ta_user_id_4284a8_idx'), models.Index(fields=['timestamp'], name='taskLogs_ta_timesta_7054aa_idx')],
            },
        ),
    ]
