# Generated by Django 5.1.6 on 2025-06-11 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskLogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklog',
            old_name='action',
            new_name='actions',
        ),
    ]
