# Generated by Django 5.1.6 on 2025-06-12 18:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0004_task_project_alter_task_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('receive_notifications', models.BooleanField(default=True, help_text='Whether the user should receive notifications about this task')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='tasks.task', verbose_name='Followed Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Follower')),
            ],
            options={
                'verbose_name': 'Task Follower',
                'verbose_name_plural': 'Task Followers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', 'user'], name='taskFollowe_task_id_01e8d9_idx'), models.Index(fields=['user', 'receive_notifications'], name='taskFollowe_user_id_970bd9_idx')],
                'unique_together': {('task', 'user')},
            },
        ),
    ]
